#!/bin/bash
# The log lebel is set in the global variable LOG_LEVEL. The choices
# are, from most to least severe, Error, Warning, Info, and Debug

function logMsg {
    message_level=$1
    message_itself=$2
    if [ $message_level -le $LOG_LEVEL ]; then 
        case $message_level in 
            0) message_level_text="Error";;
            1) message_level_text="Warning";;
            2) message_level_text="Info";;
            3) message_level_text="Debug";;
            *) message_level_text="Orther";;
        esac
        echo "${message_level_text} : $message_itself"
    fi

}

