#!/bin/bash
while [ "$1" ]
do
	if [ $1 = "-i" ]
	then
		infile=$2
		shift 2
	elif [ $1 = "-o" ]
	then
		outfile=$2
		shift 2
	else 
		echo "Program $0 doesn't recognize parameter $1"	
	fi
done

tr a-z A-Z < $infile > $outfile
