#!/bin/bash
function show_usage () {
	echo "Usage : $0 source_dir dest_dir"
    exit 0
}

function error_log () {
    if [ $# -lt 2 ]; then
        echo "Too least arguments"
        exit 1
    elif [ $# -gt 2 ]; then
        echo "Too many Arguments"
        exit 1
    fi
}

if [ $# -ne 2 ]
then
    if [ $# -eq 1 ] && [ $1 = "--help" ]
    then 
        show_usage
    fi
    echo "Function expects 2 arguments"
	error_log
	exit 1
fi 

if [ -d $1 ] && [ -d $2 ]
then 
	echo "$1 $2"
	exit 0
elif [ -d $1 ]
then 	
	echo "$2 is not a directory"
	exit 1
else
	echo "$1 is not a directory"
	exit 1
fi

